# Generated by Django 3.1.4 on 2021-02-19 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20210219_1412'),
        ('users', '0005_auto_20201212_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.customer'),
        ),
    ]
