# Generated by Django 3.1.4 on 2021-02-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='customer',
        ),
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
