# Generated by Django 3.1.4 on 2021-02-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210215_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, to='items.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, to='items.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(blank=True, to='items.Publisher'),
        ),
    ]
