# Generated by Django 3.1.4 on 2021-02-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210215_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
