# Generated by Django 3.1.4 on 2021-02-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20210217_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
