# Generated by Django 3.1.4 on 2021-02-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20210217_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
