# Generated by Django 3.1.4 on 2021-02-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20210222_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='description',
        ),
        migrations.RemoveField(
            model_name='voteoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='voteselect',
            name='description',
        ),
    ]
