# Generated by Django 3.1.4 on 2021-02-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20210222_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='voteoption',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='voteoption',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='voteselect',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='voteselect',
            name='updated_by',
        ),
    ]
