# Generated by Django 3.1.4 on 2021-02-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20210222_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='selection',
        ),
        migrations.AddField(
            model_name='vote',
            name='selection',
            field=models.ManyToManyField(blank=True, to='items.VoteOption'),
        ),
    ]
