# Generated by Django 3.1.4 on 2021-02-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_auto_20210222_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='selection',
            new_name='selections',
        ),
    ]
